Update Jenkinsfile

diff --git a/devops-test/Jenkinsfile b/devops-test/Jenkinsfile
--- a/devops-test/Jenkinsfile
+++ b/devops-test/Jenkinsfile
@@ -4,19 +4,36 @@ pipeline {
     stages {
         stage('Checkout') {
             steps {
-                git branch: 'main', url: 'https://github.com/<github_user>/devops-test.git'
+                git branch: 'main',
+                    url: 'https://github.com/percyvelle1/test-task.git'
             }
         }
 
         stage('Build & Deploy') {
             steps {
-                sshagent(['deploy-key']) {  // ID твоего SSH ключа в Jenkins
+                sshagent(['github-percyvellew-credentials']) {
                     sh '''
-                        ssh -o StrictHostKeyChecking=no debian@<IP_сервера> "
-                          cd ~/devops-test || git clone https://github.com/<github_user>/devops-test.git ~/devops-test
-                          cd ~/devops-test
+                        ssh -o StrictHostKeyChecking=no debian@82.115.48.254 "
+                          set -e
+
+                          # если нет git-репозитория, пересоздаём каталог
+                          if [ ! -d ~/devops-test/.git ]; then
+                            rm -rf ~/devops-test
+                            git clone https://github.com/percyvelle1/test-task.git ~/devops-test
+                          fi
+
+                          cd ~/devops-test/devops-test
+
+                          # обновляем репозиторий
                           git pull
-                          docker compose up -d --build
+
+                          # гарантируем, что запущено 2 реплики приложения (rolling update)
+                          docker compose up -d --scale app=2 --no-deps --build app
+
+                          # ждём, пока контейнеры приложения поднимутся
+                          sleep 5
+                          # проверка, что приложение отвечает через Nginx
+                          curl -fsS http://localhost || (echo 'App healthcheck failed' && exit 1)
                         "
                     '''
                 }
